"""Add content column to Chapter

Revision ID: 4577beca6a44
Revises: be619543c4db
Create Date: 2026-02-14 12:44:22.901781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4577beca6a44'
down_revision: Union[str, None] = 'be619543c4db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'content')
    # ### end Alembic commands ###
